services:
    jenkins:
        image: dhinojosa/jenkins-with-dep-track:2.452.3-lts
        volumes:
            - ./jenkins_home:/var/jenkins_home
        ports:
            - "8080:8080"
    vault:
      image: hashicorp/vault
      ports:
        - "8200:8200"
      command: server
      environment:
        VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      volumes:
          - ./vault_home/logs:/vault/logs
          - ./vault_home/file:/vault/file
          - ./vault_home/config:/vault/config
      cap_add:
        - IPC_LOCK
      entrypoint: vault server -config=/vault/config/vault.json

    postgres:
        image: postgres:14-alpine
        ports:
            - 5432:5432
        volumes:
            - ~/apps/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=admin123
            - POSTGRES_USER=admin
            - POSTGRES_DB=mycorp

